-- Activity gallery for the portfolio's "Galeri Kegiatan" section.
-- Run once in Supabase → SQL Editor. Safe to re-run.

-- Admin check used by the policies below: true only for a signed-in user whose profile has role = 'admin'.
-- (Being signed in is not enough — if sign-ups are open, anyone can create an account.)
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

create table if not exists public.gallery (
  id          bigint generated by default as identity primary key,
  image_url   text not null,
  caption     text,
  order_index integer not null default 0,
  created_at  timestamptz not null default now()
);

alter table public.gallery enable row level security;

-- Everyone may read; only the admin may add, edit or delete.
drop policy if exists "gallery is public" on public.gallery;
create policy "gallery is public" on public.gallery
  for select using (true);

drop policy if exists "admins manage gallery" on public.gallery;
create policy "admins manage gallery" on public.gallery
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Public bucket for the photos themselves: images only, at most 5 MB each
-- (the dashboard already shrinks uploads to ~200 KB WebP before sending them).
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('gallery-images', 'gallery-images', true, 5242880, array['image/webp', 'image/jpeg', 'image/png'])
on conflict (id) do update
  set public = true, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "gallery images are public" on storage.objects;
create policy "gallery images are public" on storage.objects
  for select using (bucket_id = 'gallery-images');

drop policy if exists "admins upload gallery images" on storage.objects;
create policy "admins upload gallery images" on storage.objects
  for insert to authenticated with check (bucket_id = 'gallery-images' and public.is_admin());

drop policy if exists "admins delete gallery images" on storage.objects;
create policy "admins delete gallery images" on storage.objects
  for delete to authenticated using (bucket_id = 'gallery-images' and public.is_admin());
